name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只在推送新标签时触发（例如 v1.0.0）

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 选择你的 Python 版本

    - name: Install Nuitka and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile prepare.py to binary
      run: |
        nuitka --standalone --onefile prepare.py

    - name: Compile hunter.py to binary
      run: |
        nuitka --standalone --onefile hunter.py

    - name: Create release directory
      run: |
        mkdir release
        cp prepare.exe release/
        cp hunter.exe release/
        cp README.md release/
        cp .env.example release/

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*  # 发布文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
