name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile prepare.py to binary
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: prepare.py
        mode: app

    - name: Compile hunter.py to binary
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: hunter.py
        mode: app

    - name: Transform README.md to PDF
      run: |
        npm i -g md-to-pdf
        md-to-pdf README.md

    - name: Create release directory
      run: |
        mkdir release
        cp build/prepare.exe release/
        cp build/hunter.exe release/
        cp README.pdf release/
        cp .env.example release/

    - name: Create a compressed archive
      run: |
        Compress-Archive -Path release/* -DestinationPath hitcoursehunter.zip -Force

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: hitcoursehunter.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: hitcoursehunter.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
