name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Nuitka and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile prepare.py to binary
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: prepare.py
        mode: app

    - name: Compile hunter.py to binary
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: hunter.py
        mode: app

    - name: Create release directory
      run: |
        mkdir release
        cp build/prepare.exe release/
        cp build/hunter.exe release/
        cp README.md release/
        cp .env.example release/

    - name: Create a compressed archive (Windows)
      run: |
        Compress-Archive -Path release/* -DestinationPath hitcoursehunter.zip -Force

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: hitcoursehunter.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
